name: Release & Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build firmware and release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jprayner/piconet-build-board-image:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build
      working-directory: ./board
      run: |
        export PICO_SDK_PATH=/pico-sdk
        cmake .
        cmake --build ./
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          README.md
          /piconet/board/piconet.uf2

  publish-ts-driver:
    name: Publish TypeScript driver to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        working-directory: ./driver/ts
        run: npm install
      - name: Build
        working-directory: ./driver/ts
        run: npm run build
      - name: Publish to npm
        working-directory: ./driver/ts
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
