name: Test board firmware build

on:
  workflow_dispatch:
  push:
    tags-ignore:
      - '**'
    paths:
      - 'board/**'
      - '.github/workflows/test-board.yaml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jprayner/piconet-build-board-image:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build
      working-directory: ./board
      run: |
        export PICO_SDK_PATH=/pico-sdk
        cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -S. -B./build
        cmake --build ./build --config Debug --target piconet -j 12 --
    - name: Archive build products
      uses: actions/upload-artifact@v3
      with:
        name: Flash image
        path: |
          ./board/build/piconet.uf2
