name: Test TypeScript Driver

on:
  push:
    tags-ignore:
      - '**'
    paths:
      - 'driver/ts/**'
      - '.github/workflows/test-driver-ts.yaml'

jobs: 
  test-driver-ts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- windows-latest
        #node: [14.x, 16.x]
        node: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install modules
        working-directory: ./driver/ts
        run: npm install
      - name: Run tests
        working-directory: ./driver/ts
        run: npm test
